// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qagalkonmnngcyzfpciu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFhZ2Fsa29ubW5uZ2N5emZwY2l1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0NTExNjIsImV4cCI6MjA3MzAyNzE2Mn0.PZmXDTjLbzSLsu7_knVZcLILexAFuc5_ojuuBq2p80U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});